### PR TITLE
latest stable version

### PR DESCRIPTION
**Pull request by DanielRuf**
many important fixes =)

### CODE REVIEW

**Comment by djtarazona** [comment]
I'll do my best to review all these changes this weekend!

**Comment by DanielRuf** [comment]
Ok thx

**Comment by lewellyn** [comment]
By the way, would it be possible for you to merge similar commits down to make this easier to review? There are 2 of a few commit messages.

**Comment by DanielRuf** [comment]
There are sometimes two because I made some corrections and fixes. Also I am for a faster development using more and smaller commits instead of big ones.

**Pull request merged**
